export const GET_EMPLOYEES_LIST = "GET_EMPLOYEES_LIST"
export const GET_EMPLOYEES_LIST_SUCCESS = "GET_EMPLOYEES_LIST_SUCCESS"

export const EMPLOYEE_LOGIN = "EMPLOYEE_LOGIN"
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS"

export const GET_EMPLOYEE_DETAILS_BY_ID = "GET_EMPLOYEE_DETAILS_BY_ID"
export const GET_EMPLOYEE_DETAILS_BY_ID_SUCCESS = "GET_EMPLOYEE_DETAILS_BY_ID_SUCCESS"

export const DELETE_EMPLOYEE_DETAILS_BY_ID = "DELETE_EMPLOYEE_DETAILS_BY_ID"
export const DELETE_EMPLOYEE_DETAILS_BY_ID_SUCCESS = "DELETE_EMPLOYEE_DETAILS_BY_ID_SUCCESS"

export const CREATE_REGISTRATION_DETAILS = "CREATE_REGISTRATION_DETAILS"
export const CREATE_REGISTRATION_DETAILS_SUCCESS = "CREATE_REGISTRATION_DETAILS_SUCCESS"

export const UPDATE_REGISTRATION_DETAILS = "UPDATE_REGISTRATION_DETAILS"
export const EDIT_REGISTRATION_DETAILS = "EDIT_REGISTRATION_DETAILS"